# profiler-hub
[components.lib."profiler/profiler-hub/stage"]
include = [
  "lib/libprofiler-hub.so*",
]
[components.dbg."profiler/profiler-hub/stage"]
[components.dev."profiler/profiler-hub/stage"]
include = [
  "include/profiler-hub/**",
  "lib/libprofiler-hub.a",
  "lib/cmake/profiler-hub/**",
]
[components.doc."profiler/profiler-hub/stage"]
